### PR TITLE
Enhancements: realtime update for textbox and support for nested yaml structures

### PR DESCRIPTION
**Pull request by snootched**
For review are some enhancements that were made in support of a project I'm working on.
(I'm no pro and consulted/fought with an llm to get most of this achieved to satisfaction.)

I have a requirement to support nested/complex yaml structures as well as supporting arrays in the yaml.

These enhancements add

- a deepMerge function and update the event handler code
- support for arrays within nested yaml
- listen for input event on textbox control (may be chatty, but enables realtime updates to the yaml and card preview while typing in a textbox)

### CODE REVIEW

**Comment by marcokreeft87** [comment]
Please put all the indenting back. I will review the rest on Friday. Thanks for the help!

**Comment by snootched** [comment]
Sorry about that - I think it should be all back in place now.
Also removed an unused import in controls.ts that I had added when trying a previous approach to this.

Thanks for considering, and thanks for this project it's really helpful!
(I'm pulling the form configs in via yaml for my use case, but it's wip still)

This is the card structure achieved by the update:
```yaml
type: custom:cb-lcars-label-card
cblcars_card_config:
  show_label: true
  variables:
    text:
      label:
        font_size: 18px
    check_boxes:
      - ITEM_1
      - ITEM_2
    entity: light.tv
  label: My Nested Label
label: My Test label
```

This is the test form:

```yaml
cb-lcars-label-card:
  render_form:
    - controls:
        - label: "Label (standard variable)"
          configValue: "label"
          type: !FormControlType Textbox
        - label: Label (nested variable)
          configValue: cblcars_card_config.label
          type:  !FormControlType Textbox
        - label: Font Size
          configValue: cblcars_card_config.variables.text.label.font_size
          type: !FormControlType Textbox
    - label: "Group of controls"
      controls:
        - label: "Some checkboxes"
          configValue: cblcars_card_config.variables.check_boxes
          type: !FormControlType Checkboxes 
          items:
            - value: ITEM_1
              label: 'item 1'
            - value: ITEM_2
              label: 'item 2'
        - label: "Light Entity"
          configValue: cblcars_card_config.variables.entity
          type: !FormControlType EntityDropdown
          domain: light
  css: |
    ha-textfield {
      width: 75%;
    }
  ```

**Comment by marcokreeft87** [comment]
I'm look at the added features and my first thought was "I already have those features in it" . Then I saw your yaml and I think you are using the code in a different way than intended. 
This project is a npm package that you can use to render the editor for you lovelace card. Check out the example here:
https://github.com/marcokreeft87/ha-editor-formbuilder?tab=readme-ov-file#example-usage

Or am I assuming wrong?

**Comment by snootched** [comment]
Apologies, I probably confused things in my previous comment the second yaml isn't part of this PR - its just how I've implemented in my card to set up the forms.  Storing them in yaml makes it easier for me to tweak forms as I go - I know that part is not the intended way of setting up the forms in formbulider.


What I was after with this particular enhancement,  adding the 'deepmerge', was to support more complex configs in the the card.  Unless I've missed something (whis is completely possible!) the current formbuilder code was not generating the desired yaml.

In this example, the desired outcome of the form is to generate this yaml for the custom card confg:

```yaml
type: custom:cb-lcars-label-card
cblcars_card_config:
  show_label: true
  variables:
    text:
      label:
        font_size: 18px
    entity: light.front_door
  label: nested label
  templates:
    - cb-lcars-state-blink
    - cb-lcars-actions-disable
label: outer label
```

If we look at `font_size` variable, the path is `cblcars_card_config.variables.text.label.font_size`

```
controls: [  { label: "Font Size", configValue: "cblcars_card_config.variables.text.label.font_size", type: FormControlType.Textbox }                ]
```

Initially this was ending up in the card such as this:
```yaml
type: custom:cb-lcars-label-card
cblcars_card_config.variables.text.label.font_size: 18px
.
.
```

The array part was to allow for arrays nested downlevel in the yaml structure.  You could add/remove items from the array with the checkboxes on the form - a user could add more items to the array if they switched code editor mode to type in more.  It  will take into account that if the user does add something and switch back and forth between visual/code editor modes, the user's item won't be lost.


Hopefully that makes sense what I was trying to achieve - but definitely if I've missed something please let me know :)

**Comment by marcokreeft87** [comment]
So basically the deepmerge was to support the yaml definition?

**Comment by snootched** [comment]
The deepmerge is to support the generation/updating of the card's yaml that the formbuilder touches, yes.
The web controls on the form, in this card, are required to insert/update/remove the config values that may be nested - but we don't want to affect other parts of the structure.

**Comment by marcokreeft87** [comment]
Than I don't see any changes that will take this library forward. The yaml feature isn't anything you can use to use the card in the editor view.

**Comment by snootched** [comment]
I'm not sure I understand your comment, but I do appreciate your time and consideration.
We can close this off if you do not see any benefit for this.

This is what I was going for in HA editor:

image


would yield:

image


and if you were to add something within the yaml side, it will get merged properly and not clobbered.

image

**Comment by marcokreeft87** [comment]
I can see the benefit for it using YAML. But dId you test it with a javascript coded card? Otherwise it will break more than it will add you know what I mean?

**Comment by snootched** [comment]
Ah ok, I think I (mostly) see what you're saying.  I took a look at your formula one card (very cool btw!)
I'll close this one down, as what I'm doing is an edge case.
The other changes made you may want to consider, or not, in the future (card preview updating while typing in textboxes, and the form controls updating their state if the user changes the value on the yaml side of the config for some reason.)

Otherwise thank you very much for your time and consideration, I do appreciate it!

**Comment by marcokreeft87** [comment]
No problem! Thnx for the suggestions

**Pull request closed without merging**
